"""Glyph-v2 sweep: replace the v1 terrain camera-frame glyph with v2 in
every stored figure (rows 7-18; rows 1-6 are regenerated by re-running
archive/arch_svg_reference.py, which now emits v2 via
terrain_frame_glyph.terrain_frame).

v1 -> v2 (autoresearch/prompt.md): street strokes inset so their caps no
longer overflow the frame border (M26..L102 w6 -> M31..L97 w5;
M62/48 w4 -> M59/49 w3.5), buildings/park/dots nudged inside, and the
group wrapper now carries id='cam-terrain', which the updated
figcheck.check() requires on every figure.

Each row is one asserted replacement of the exact v1 string previously
deployed (terrain_frame_v1 at that row's frame-top Y; row 7's glyph was
inserted unwrapped inside the figure's existing <g>, and its v2
replacement nests the marked group there; row 18 is the agent's verbatim
copy of the old prompt snippet at Y=112). Safe to re-run: an already-
swept figure fails the count assert instead of double-patching.

Usage: .venv/bin/python archive/align_svg_glyph_v2.py [row ...]
(defaults to rows 7-18; run on the pod against the pod's
experiments.sqlite — back it up first:
cp experiments.sqlite experiments.sqlite.bak-figfix5)
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
sys.path.insert(0, str(Path(__file__).resolve().parent))
from autoresearch.db import connect
from terrain_frame_glyph import terrain_frame, terrain_frame_v1

# row -> (frame-top Y, v1 was wrapped in a plain <g>)
FRAME_Y = {7: (82, False), 8: (74, True), 9: (74, True), 10: (74, True),
           11: (74, True), 12: (74, True), 14: (74, True), 15: (74, True),
           16: (110, True), 17: (110, True), 18: (112, True)}

PATCHES = {row: [(terrain_frame_v1(y, wrap_g=wrapped), terrain_frame(y), 1)]
           for row, (y, wrapped) in FRAME_Y.items()}


def main():
    rows = [int(a) for a in sys.argv[1:]] or sorted(PATCHES)
    conn = connect()
    for exp_id in sorted(rows):
        svg = conn.execute("SELECT arch_svg FROM experiments WHERE id=?",
                           (exp_id,)).fetchone()[0]
        for old, new, expect in PATCHES[exp_id]:
            n = svg.count(old)
            assert n == expect, (
                f"exp {exp_id}: expected {expect}x v1 glyph, found {n} — "
                f"already swept or figure changed; aborting unmodified")
            svg = svg.replace(old, new)
        conn.execute("UPDATE experiments SET arch_svg=? WHERE id=?",
                     (svg, exp_id))
        print(f"exp {exp_id}: camera glyph v1 -> v2 (cam-terrain)")
    conn.commit()
    conn.close()


if __name__ == "__main__":
    main()
